name: Deploy Qora Frontend

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build

      - name: Copy Built static files to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/*"
          target: "/var/www/qora/fe-dist"
          strip_components: 1 # Copies contents of dist/ directly into fe-dist/
